### ISSUE TITLE
Thank you for updating the EFI

### ISSUE THREAD

**Issue by JulindM** [littlegtplr/Hackintosh-X230-macOS#7]
This is no issue, but after hours of having audio problems with my x230 on 10.15.4 I stumbled upon this gem of an EFI folder and it pretty much fixed all my problems not just the audio ones (slow bootup, bad kexts, etc) and I just want to appreciate the hard work put into this repo. Thank you! You have probably saved me and others days of extra work 🙏

**Comment by littlegtplr** [comment]
No worries at all! Glad it's helpful and solves your issues!
